### ISSUE TITLE
[BUG] [Doxygen] XML Parsing Error: duplicate attribute

### ISSUE THREAD

**Issue by xgupta** [TheAlgorithms/C-Plus-Plus#1201]
## Description

The call graph should be shown in the doxygen documentation. But not available for many functions. See one https://thealgorithms.github.io/C-Plus-Plus/df/dfb/minimax_8cpp.html#ae66f6b31b5ad750f1fe042a706a4e3d4. 

## Expected Behavior

Call graph should be visible.

## Actual Behavior

Error state that XML Parsing Error: duplicate attribute
Location: https://thealgorithms.github.io/C-Plus-Plus/df/dfb/minimax_8cpp_ae66f6b31b5ad750f1fe042a706a4e3d4_cgraph.svg
Line Number 24, Column 102:

## Possible Fix

After make doc run the `doxygen Doxyfile.doc`. but I don't know where will this action made in https://github.com/TheAlgorithms/C-Plus-Plus.

## Steps to Reproduce

1. Search any page for exmaple https://thealgorithms.github.io/C-Plus-Plus/d4/d8d/jarvis__algorithm_8cpp.html

## Context

The call graph makes it easier to understand the program.

**Comment by kvedala** [comment]
Good catch. Thanks for pointing out. It seems that the SVG being generated by doxygen is invalid. This bug has already been reported and apparently fixed on their master branch. https://github.com/doxygen/doxygen/issues/8053
Once the fix is updated on the minor revision, it should trickle down to the the corresponding [brew](https://formulae.brew.sh/formula/doxygen)

**Comment by xgupta** [comment]
It seems issue is solved now? Above doxygen webpage is displaying correctly.
