### ISSUE TITLE
[BUG] Misconfiguration of CMake in the `graphics` folder

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#2401]
### Description

The `graphics` directory uses GLUT (or FreeGlut) to compile. When it cannot find GLUT, it will use FreeGlut instead.
However, it seems that there's a wrong or missing configuration of CMake for that directory.

https://github.com/TheAlgorithms/C-Plus-Plus/actions/runs/3595016533/jobs/6054004314#step:4:1248

I tried investigating further for that and tried a few stuff, but none of those changes worked.
I even tried with the old link (which was changed to GitHub at https://github.com/TheAlgorithms/C-Plus-Plus/commit/d0f7f230cad38b7d55a5190a8604b9d649b78910 and it [**worked fine**](https://github.com/TheAlgorithms/C-Plus-Plus/actions/runs/3518179849/jobs/5896813163), because it was showing errors in #2396) and it still showed the same error message.

### Expected behavior

CMake should not throw an error message stating that it cannot find `freeglut.lib`.

### Actual behavior

CMake cannot find `freeglut.lib` which makes the CI tests fail.

### Context

This should be fixed immediately as it prevents the Windows checks to verify if the code is running and working as excepted.

**Comment by MaximSmolskiy** [comment]
@Panquesito7 I think the problem is that now the `freeglut` doesn't compile.
Because in early logs (when it worked fine) there was:
```
-- Could NOT find GLUT (missing: GLUT_glut_LIBRARY) 
FreeGLUT library will be downloaded and built.
```
but now:
```
-- Found GLUT: C:/Strawberry/c/lib/libglut.a
```
And now it finds some strange `GLUT` - because as I know `.a` is extension of static libraries in `Linux`, not in `Windows`.
So, I think that now it finds incorrect `GLUT`, because of that doesn't compile `freeglut` and then can't find correct `GLUT` library for linking.
I think that behaviour can have changed due to difference in `Runner Image` versions, but I'm not sure.

As solution, maybe forcing to compile `freeglut` will help (ignoring `if(NOT GLUT_FOUND)`)

**Comment by Panquesito7** [comment]
Hey! Thanks for checking out the issue. 😄

> As solution, maybe forcing to compile `freeglut` will help (ignoring `if(NOT GLUT_FOUND)`)

Would you like to make a PR for that or should I try it out myself?

**Comment by MaximSmolskiy** [comment]
> Hey! Thanks for checking out the issue. 😄
> 
> > As solution, maybe forcing to compile `freeglut` will help (ignoring `if(NOT GLUT_FOUND)`)
> 
> Would you like to make a PR for that or should I try it out myself?

I'll make a PR soon
