### ISSUE TITLE
New directory proposal (Competitive-Coding)

### ISSUE THREAD

**Issue by ashneg** [TheAlgorithms/C-Plus-Plus#259]
I would like to propose an idea of adding a new directory for **Competitive-Coding** . This would help people who are new to programming implement those algo's .

I have been doing competitive coding from last 2 years on the platform's like **Codechef, Codeforces, Top-coder, Hackerearth** and would like to contribute my successfully submitted code to this repo.

**Please assign me this task**

**Comment by fhlasek** [comment]
@ashneg I believe that this repo's main purpose is to gather general algorithms rather than contain a repository of solutions to specific problems from competitions. Furthermore, there is a focus on the clarity of the implementation while in programming competitions speed and briefness are often more important factors. Closing this issue.

**Comment by kvedala** [comment]
An addendum: 
Many competitive coding challenges involve application of a certain algorithm or a certain type of algorithm. These algorithms should fit into one of the folders of the repo. There are many contributions in the repo that have originated from competitive coding challenges. As advised above, please review the guidelines and feel free to contribute accordingly.
